src/Entity/Promotions.php
<?php

namespace App\Entity;

use App\Entity\Trait\CreatedAtTrait;
use App\Entity\Trait\SlugTrait;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\DBAL\Types\Types;
use App\Repository\PromotionsRepository;

#[ORM\Entity(repositoryClass: PromotionsRepository::class)]
class Promotions
{
    use CreatedAtTrait;
    use SlugTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue(strategy:"AUTO")]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Products::class, inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private $products;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_deb = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(type: 'integer')]
    private $pourcentage;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDeb(): ?DateTime
    {
        return $this->date_deb;
    }

    public function setDateDeb(\DateTimeInterface $date_deb): self
    {
        $this->date_deb = $date_deb;

        return $this;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;
        
        return $this;
    }

    public function getDateFin(): ?DateTime
    {
        return $this->date_fin;
    }

    public function getProducts(): ?Products
    {
        return $this->products;
    }

    public function setProducts(?Products $products): self
    {
        $this->products = $products;

        return $this;
    }

    public function setPourcentage(int $pourcentage): self
    {
        $this->pourcentage = $pourcentage;

        return $this;
    }

    public function getPourcentage(): ?int
    {
        return $this->pourcentage;
    }
}

src/Controller/Admin/CategoriesController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Categories;
use App\Form\CategoryFormType;
use App\Repository\CategoriesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/admin/categories', name: 'admin_categories_')]
class CategoriesController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(CategoriesRepository $categoriesRepository): Response
    {
        $categories = $categoriesRepository->findBy([], ['categoryOrder' => 'asc']);

        return $this->render('admin/categories/index.html.twig', compact('categories'));
    }

    #[Route('/ajout', name: 'add')]
    public function add(Request $request, EntityManagerInterface $em, SluggerInterface $slugger): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        $category = new Categories();

        // On crée le formulaire
        $categoryForm = $this->createForm(CategoryFormType::class, $category);

        // On traite la requête du formulaire
        $categoryForm->handleRequest($request);

        //On vérifie si le formulaire est soumis ET valide
        if ($categoryForm->isSubmitted() && $categoryForm->isValid()) {
            // On récupère les images

            // On génère le slug
            $slug = $slugger->slug($category->getName());
            $category->setSlug($slug);

            // On stocke
            $em->persist($category);
            $em->flush();

            $this->addFlash('success', 'Catégorie ajouté avec succès');

            // On redirige
            return $this->redirectToRoute('admin_categories_index');
        }

        return $this->render('admin/categories/add.html.twig',[
            'categoriesForm' => $categoryForm->createView()
        ]);
    }

    #[Route('/suppression/{id}', name: 'delete')]
    public function delete(Categories $categorie, EntityManagerInterface $em): Response
    {
        // On vérifie si l'utilisateur peut supprimer avec le Voter
        $this->denyAccessUnlessGranted('ROLE_ADMIN', $categorie);

        if (!$categorie) {
            // Si le produit n'existe pas, on retourne une erreur 404
            throw $this->createNotFoundException('La catégorie n\'existe pas');
        }

        // On supprime le produit
        $em->remove($categorie);
        $em->flush();

        $this->addFlash('success', 'Catégorie supprimée avec succès');

        return $this->redirectToRoute('admin_categories_index');
    }

    #[Route('/edition/{id}', name: 'edit')]
    public function edit(Categories $category,Request $request, EntityManagerInterface $em, SluggerInterface $slugger): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        // On crée le formulaire
        $categoryForm = $this->createForm(CategoryFormType::class, $category);

        // On traite la requête du formulaire
        $categoryForm->handleRequest($request);

        //On vérifie si le formulaire est soumis ET valide
        if ($categoryForm->isSubmitted() && $categoryForm->isValid()) {
            // On récupère les images

            // On génère le slug
            $slug = $slugger->slug($category->getName());
            $category->setSlug($slug);

            // On stocke
            $em->persist($category);
            $em->flush();

            $this->addFlash('success', 'Catégorie modifiée avec succès');

            // On redirige
            return $this->redirectToRoute('admin_categories_index');
        }

        return $this->render('admin/categories/edit.html.twig',[
            'categoriesForm' => $categoryForm->createView()
        ]);
    }
}

src/Controller/CategoriesController.php
<?php

namespace App\Controller;

use App\Entity\Categories;
use App\Repository\ProductsRepository;
use App\Repository\PromotionsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/categories', name: 'categories_')]
class CategoriesController extends AbstractController
{
    #[Route('/{slug}', name: 'list')]
    public function list(Categories $category, ProductsRepository $productsRepository,PromotionsRepository $promotionsRepository, Request $request): Response
    {
        //On va chercher le numéro de page dans l'url
        $page = $request->query->getInt('page', 1);

        //On va chercher la liste des produits de la catégorie
        $products = $productsRepository->findProductsPaginated($page, $category->getSlug(), 4);
        $promotions = $promotionsRepository->findAll();

        return $this->render('categories/list.html.twig', [
            'category' => $category,
            'products' => $products,
            'promotions' => $promotions,
        ]);
    }
}

templates/categories/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des produits de la catégorie
	{{ category.name }}
{% endblock %}

{% block body %}
	<main class="container">
		<section class="row">
			<div class="col-12">
				<h1 class="titreCat">Liste des produits de la catégorie
					{{ category.name }}</h1>
			</div>

			{% if products.data is not defined %}
				<div class="col-12">
					<p>Aucun produit dans cette catégorie.</p>
				</div>
			{% else %}
				{% for product in products.data %}
					<div class="col-4 oneProduct">
						<div class="card h-100">
							<div class="card-body">
									{% if product.images is not empty %}
										{% for image in product.images %}
											<img src="{{ asset('assets/uploads/products/mini/300x300-' ~ image.name) }}" alt="{{ product.name }}" class="img-thumbnail" width='150px'>
										{% endfor %}
									{% endif %}
								<h3 class="card-title">{{ product.name }}</h3>
								<p class="card-text">{{ product.description }}</p>
								{% set promotion = null %}
								{% for promo in promotions %}
									{% if promo.products.id == product.id and promo.dateDeb|date("m/d/Y") <= 'now'|date("m/d/Y") and promo.dateFin|date("m/d/Y") >= 'now'|date("m/d/Y") %}
										{% set promotion = promo %}
									{% endif %}
								{% endfor %}
								{% if promotion is not null %}
									<p class="card-text">
										{% set discountedPrice = product.price - (product.price * promotion.pourcentage / 100) %}
									</p>
									<p style="color:red;">
										<b>Prix promotionnel:
											{{ discountedPrice|number_format(2) }}
											€ / -{{promotion.pourcentage}}
											%
											<br>
											Remise valable du
											{{promotion.dateDeb|date("d/m/Y")}}
											au
											{{promotion.dateFin|date("d/m/Y")}}</b>
									</p>
								{% else %}
									<p class="card-text">Prix :
										{{ product.price|number_format(2) }}
										€</p>
								{% endif %}
							</div>
						</div>
					</div>
				{% endfor %}
				{% set path = 'categories_list' %}
				{% set slug = category.slug %}
				{% set pages = products.pages %}
				{% set currentPage = products.page %}
				{% include "_partials/_pagination.html.twig" %}
			{% endif %}

		</section>
	</main>
{% endblock %}